import Head from "next/head";
import { gql } from "@apollo/client";
import { client } from "../lib/apollo";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { GET_ALL_POSTS, GET_HOME_PAGE } from "../lib/queries";

export default function Home({ posts, homePageTitle, homePageContent }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1
          className={styles.title}
          dangerouslySetInnerHTML={{ __html: homePageTitle }}
        />
        <div dangerouslySetInnerHTML={{ __html: homePageContent }} />

        <ul>
          {posts.map(({ title, slug, date }) => (
            <li key={slug}>
              <Link href={`/blog/${slug}`}>
                <a>
                  [{date}] {title}
                </a>
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const homePageContent = await client.query({
    query: GET_HOME_PAGE,
  });

  const allPosts = await client.query({
    query: GET_ALL_POSTS,
  });

  return {
    props: {
      posts: allPosts.data.posts.nodes,
      homePageTitle: homePageContent.data.pageBy.title,
      homePageContent: homePageContent.data.pageBy.content,
    },
  };
}
